import imp
import morven_cube_server.routes.handle_sensor_get
import morven_cube_server.routes.handle_pattern_patch
import morven_cube_server.routes.handle_pattern_get
import morven_cube_server.routes.handle_verified_pattern
import morven_cube_server.routes.handle_runthroughs_get

from morven_cube_server.routes.routes_object import routes
